services:
  k0s:
    container_name: k0s
    image: docker.io/k0sproject/k0s:v1.27.4-k0s.0
    command: k0s controller --config=/etc/k0s/config.yaml --single
    hostname: k0s
    privileged: true
    cgroup: host
    volumes:
      - ./k0sconfig.yaml:/etc/k0s/config.yaml
      - ./containerd.toml:/etc/k0s/containerd.toml
      # - ./manifests/gatewayCrds:/var/lib/k0s/manifests/gtw
      - /var/lib/k0s

      # - /sys/fs/cgroup:/sys/fs/cgroup:shared
      - /sys/fs/cgroup:/run/cilium/cgroupv2:shared
      - /run/udev:/run/udev:slave
      - /sys/fs/bpf:/sys/fs/bpf:shared
    ports:
      - "6443:6443"
      - "80:80"
      - "443:443"
    network_mode: "bridge"
    # network_mode: "host"
#     networks:
#       k0s_network:
#         ipv4_address: 172.69.2.2

# networks:
#   k0s_network:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.69.0.0/16
