services:
  k0s:
    container_name: k0s
    image: docker.io/k0sproject/k0s:v1.27.4-k0s.0
    command: k0s controller --config=/etc/k0s/config.yaml --single
    # command: k0s controller --enable-worker --single
    hostname: k0s
    privileged: true
    cgroup: host
    # cgroup_parent: docker-k0s.slice
    volumes:
      - ./k0sconfig.yaml:/etc/k0s/config.yaml
      - ./manifests:/var/lib/k0s/manifests/gatewayCRDs
      - /var/lib/k0s
      - /sys/fs/cgroup:/sys/fs/cgroup:shared
      - /run/cilium/cgroupv2:/run/cilium/cgroupv2:shared
      - /run/udev:/run/udev
      - /sys/fs/bpf:/sys/fs/bpf:shared
    tmpfs:
    - /run
    - /var/run
    ports:
      - "6443:6443"
      - "80:80"
      - "443:443"
    network_mode: "bridge"
