apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: k0s
spec:
  api:
    address: 172.17.0.2
    port: 6443
    # externalAddress: 172.17.0.2
    sans:
      - 172.17.0.2
      - 172.17.0.3
      - 172.17.0.4
      - 172.17.0.5
      - 10.96.0.1
  extensions:
    helm:
      repositories:
        - name: cilium
          url: https://helm.cilium.io/
      charts:
        - name: cilium
          chartname: cilium/cilium
          # version: "1.15.0-pre.0"
          version: "1.14.1"
          namespace: kube-system
          values: |
            kubeProxyReplacement: true
            k8sServiceHost: 172.17.0.2
            k8sServicePort: 6443
            operator:
              replicas: 1
            # envoy:
            #   enabled: true
            # debug:
            #   enable: true
            #   verbose: envoy
            l2announcements:
              enabled: true
            devices: "eth0"
            externalIPs:
              enabled: true
            nodePort:
              enabled: true
            gatewayAPI:
              enabled: true
            image:
              pullPolicy: IfNotPresent
            ipam:
              mode: kubernetes
              # operator:
              #   clusterPoolIPv4PodCIDRList: "10.42.0.0/16"
            hubble:
              enabled: true
              ui:
                enabled: true
              relay:
                enabled: true
  network:
    provider: custom
    kubeProxy:
      disabled: true
  storage:
    type: kine
