#l2announcementpolicy
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-policy
  namespace: kube-system
spec:
  serviceSelector:
    matchLabels:
      io.cilium.gateway/owning-gateway: sgtw
  interfaces:
    - eth0 #your interface regex
  externalIPs: true
  loadBalancerIPs: true
